---
name: Release

"on":
  release:
    types: [published]

jobs:
  crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-stable-cargo-v1-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-stable-cargo-v1-

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_TOKEN}} -v --all-features
