---
name: Shell

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Lint code with Shellcheck
        uses: ludeeus/action-shellcheck@1.1.0

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Run shfmt
        uses: luizm/action-sh-checker@v0.3.0
        with:
          sh_checker_shellcheck_disable: true
